name: Pull request

on:
    push:
        branches:
            - master
            - develop
    pull_request:
        branches:
            - '**'

jobs:
    docker:
        timeout-minutes: 10
        runs-on: ubuntu-latest

        steps:
            # 해당 저장소의 코드를 가져옵니다.
            - name: Checkout
              uses: actions/checkout@v2

            # Node 16 버전을 사용합니다.
            - name: Install node
              uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  cache: 'npm'

            # yarn을 설치합니다.
            - name: Install Yarn
              run: npm install yarn

            # 설치된 yarn을 통해 패키지를 설치합니다.
            - name: Install dependencies
              run: yarn install

            # 테스트를 수행합니다.
            - name: Run tests
              run: yarn test

            - name: if_fail
              uses: actions/github-script@v4
              with:
                  github-token: ${{ secrets.TOKEN }}
                  script: |
                      const ref = "${{github.ref}}"
                      const pull_number = Number(ref.split("/")[2])
                      console.log(pull_number, ref.split("/"), github.ref)
                      await github.pulls.createReview({
                        ...context.repo,
                        pull_number,
                        body : "테스트코드를 다시 확인해주세요. ",
                        event : "REQUEST_CHANGES"
                      })
                      await github.pulls.update({
                        ...context.repo,
                        pull_number,
                        state: "closed"
                      })
              if: failure()
